# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H--fGm6BTnpwYkAGjSCchbzja3JfKgK2
"""

#  calculate simple intrest.

# principle_amount = float(input("enter the amount:"))
# Rate = float(input("enter the rate:"))
# Time = float(input("enter the time:"))
# SI = (principle_amount*Rate*Time)/100
# print(f"Simple Intrest: {SI}")
# Total_amount = principle_amount + SI
# print(f"Total amount you pay:{Total_amount}")


# calculate the simple intrest.
Principle_amount = float(input("enter the amount:"))
Rate = float(input("enter the rate:"))
Time = int(input("enter the year"))
T_Days = float(input("enter the days:"))
SI_Mon = (Principle_amount*Rate*Time)/100
SI_Day = (Principle_amount*Rate*T_Days)/100*30
SI = SI_Mon+SI_Day
print(f"Simple Intrest: {SI}")
Total_amount = Principle_amount+SI
print(f"Total amount you pay:{Total_amount}")

def sum_of_numbers():
    total_sum = 0
    n = int(input("enter the number:"))
    for i in range(1, n + 1):
        total_sum += i
    return total_sum

result = sum_of_numbers()
print(result)